spring:
  profiles:
   active: dev

  application:
    name: employee

# Local MariaDB datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
     connection-timeout: 120000
     idle-timeout: 120000
     connection-test-query: SELECT 1
     validation-timeout: 120000

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            "[non_contextual_creation]": true
        dialect: org.hibernate.dialect.MariaDBDialect
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update

  main:
    allow-circular-references: true


info:
  app:
    name: Employee Application
    version: 0.0.1
  id: empapp


# Enable Gzip compression
server:
  port: 5000
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript

  error:
    include-message: always
    include-binding-errors: always